name: CD

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{secrets.AWS_REGION}}
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_ACCESS_KEY_SECRET}}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull Docker image from ECR
        run: |
          docker pull ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_REPO }}:${{ secrets.AWS_IMAGE_TAG }}

      - name: Deploy Docker container
        run: |
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 80:80 ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_REPO }}:${{ secrets.AWS_IMAGE_TAG }}