name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{secrets.AWS_REGION}}
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_ACCESS_KEY_SECRET}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull Docker image from ECR
        env:
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_SECRET}}
        run: |
          sudo docker pull ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_REPO }}:${{ secrets.AWS_IMAGE_TAG }}

      - name: Deploy Docker container
        run: |
          sudo docker stop my-app || true
          sudo docker rm my-app || true
          sudo docker run -d --name my-app -p 80:80 ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_REPO }}:${{ secrets.AWS_IMAGE_TAG }}